apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: frontend
          servicePort: 80

